export const TRANSACTION_EVENT = "NEW_TRANSACTION";
export const NEW_BLOCKS_EVENT = "NEW_BLOCKS";
export const NEW_BLOCKS_FROM_DEPTH_EVENT = "NEW_BLOCKS_FROM_DEPTH_EVENT";
export const EVENTS_EVENT = "NEW_EVENTS";
