FROM golang:1.23.7 AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o create-coinbase ./create-coinbase/create-coinbase.go

FROM scratch
WORKDIR /app
COPY ./global-bundle.pem ./global-bundle.pem
COPY --from=builder /app/create-coinbase .
CMD ["./create-coinbase"]
