import { sequelize } from '../config/database';
import Pair from '../models/pair';
import Token from '../models/token';

interface CreatePairParams {
  moduleName: string;
  name: string;
  parameterText: string;
  parameters: string;
  qualifiedName: string;
  chainId: number;
}

interface TokenReference {
  refName: {
    name: string;
    namespace: string | null;
  };
  refSpec: Array<{
    name: string;
    namespace: string | null;
  }>;
}

export class PairService {
  /**
   * Creates a token if it doesn't exist
   * @param tokenRef Token reference from the parameters
   * @param transaction Sequelize transaction
   * @returns Created or found token
   */
  private static async createOrFindToken(
    tokenRef: TokenReference,
    transaction: any,
  ): Promise<Token> {
    const tokenName = tokenRef.refName.name;
    const tokenNamespace = tokenRef.refName.namespace || '';

    const [token] = await Token.findOrCreate({
      where: {
        code: `${tokenNamespace}.${tokenName}`,
      },
      defaults: {
        id: 0, // This will be auto-generated by the database
        code: `${tokenNamespace}.${tokenName}`,
        icon: '', // Default empty icon
        tokenName: tokenName,
        tokenSymbol: tokenName.toUpperCase(),
        tokenInfo: {
          decimalsToDisplay: 8,
          description: '',
          themeColor: '#000000',
          discordUrl: '',
          mediumUrl: '',
          telegramUrl: '',
          twitterUrl: '',
          websiteUrl: '',
        },
        validated: false,
      },
      transaction,
    });

    return token;
  }

  /**
   * Creates tokens if they don't exist and then creates a pair
   * @param pairs Array of pair creation parameters
   */
  static async createPairs(pairs: CreatePairParams[]): Promise<void> {
    if (!pairs || pairs.length === 0) {
      return;
    }

    for (const pair of pairs) {
      await sequelize.transaction(async t => {
        // Parse parameters to get token information
        const params = JSON.parse(pair.parameters);
        const token0Ref = params[0] as TokenReference;
        const token1Ref = params[1] as TokenReference;
        const key = params[2] as string;

        // Create or find both tokens
        const [token0, token1] = await Promise.all([
          this.createOrFindToken(token0Ref, t),
          this.createOrFindToken(token1Ref, t),
        ]);

        // Create pair
        await Pair.create(
          {
            token0Id: token0.id,
            token1Id: token1.id,
            reserve0: '0',
            reserve1: '0',
            totalSupply: '0',
            key: key,
          },
          { transaction: t },
        );
      });
    }
  }

  /**
   * Updates pairs based on the provided update events
   * @param updateEvents Array of pair update events
   */
  static async updatePairs(
    updateEvents: Array<{
      moduleName: string;
      name: string;
      parameterText: string;
      parameters: string;
      qualifiedName: string;
      chainId: number;
    }>,
  ): Promise<void> {
    for (const event of updateEvents) {
      try {
        // Parse the parameters
        const [key, reserve0, reserve1] = JSON.parse(event.parameters);

        // Find the pair by key
        const pair = await Pair.findOne({
          where: { key },
        });

        if (!pair) {
          console.warn(`Pair not found for key: ${key}`);
          continue;
        }

        // Update the reserves
        await pair.update({
          reserve0: reserve0.toString(),
          reserve1: reserve1.toString(),
        });
      } catch (error) {
        console.error('Error updating pair:', error);
      }
    }
  }
}
